---
- name: Create a new user on multiple servers
  hosts: clients
  become: yes

  vars_files:
    - passwords.yml

  vars_prompt:
    - name: username
      prompt: "Podaj nazwę nowego użytkownika"
      private: no
    - name: ssh_pubkey
      prompt: "Podaj klucz publiczny dla nowego użytkownika"
      private: no
    - name: password
      prompt: "Podaj hasło dla nowego użytkownika"
      private: yes

  vars:
    ansible_ssh_pass: "{{ servers[inventory_hostname].ssh }}"
    ansible_become_pass: "{{ servers[inventory_hostname].sudo }}"

  tasks:
    - name: Add new user
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Set password for new user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"

    - name: Create SSH directory for new user
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add authorized key
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_pubkey }}"
